[CON-861] [CON-862] Stop symlinks/hardlinks from causing enclave crash
# Changes
- Attempts to create symlinks or hardlinks inside the enclave will no longer cause the enclave to crash. An exception is thrown to the user instead.

# Example stack trace:
```
java.nio.file.FileSystemException: (symlink|link) -> <link-directory>: 
    at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:491)
    at java.nio.file.Files.createLink(Files.java:1112)
    at com.r3.conclave.sample.enclave.ReverseEnclave.onStartup(ReverseEnclave.java:23)
    at com.r3.conclave.enclave.Enclave$StartCallHandler.handleCall(Enclave.kt:580)
    at com.r3.conclave.common.internal.CallInterface.handleIncomingCall(CallInterface.kt:48)
    at com.r3.conclave.enclave.internal.NativeEnclaveHostInterface.handleCallECall(NativeEnclaveHostInterface.kt:93)
    at com.r3.conclave.enclave.internal.NativeEnclaveHostInterface.handleECall(NativeEnclaveHostInterface.kt:64)
    at com.r3.conclave.enclave.internal.NativeEnclaveEnvironment$Companion.enclaveEntry(NativeEnclaveEnvironment.kt:58)
    at com.r3.conclave.enclave.internal.NativeEnclaveEnvironment.enclaveEntry(NativeEnclaveEnvironment.kt)
    at com.r3.conclave.enclave.internal.substratevm.EntryPoint.entryPoint(EntryPoint.java:23)
```